version: '2.3'
services:
  flask-reload:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    environment:
      PYTHONPATH: .
    ports:
	- '2000:2000'
	- '2001:2001'
